//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaBancaria
    {
        public int Numero_cuenta { get; set; }
        public Nullable<int> Cedula { get; set; }
        public Nullable<System.DateTime> Fecha_apertura { get; set; }
        public Nullable<decimal> Monto { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
